name: rok
channels:
  - conda-forge
dependencies:
  - reaktoro
  - python=3.7
  - pytest
  - pytest-regressions
  - numpy
  - pandas
  - gstools
  - pre-commit
  - black

environment:
  PYTHONPATH:
    - {{ root }}:$CONDA_PREFIX/lib/python3.7/site-packages

  PATH:
    - {{ PATH }}:{{ root }}/firedrake/bin
